### ISSUE TITLE
test expecting a config file

### ISSUE THREAD

**Issue by lheagy** [ucgmsim/GMSimViz#19]
It looks like the test `test_gmt` requires a config file. Is there one that can be included in the test directory? 
```
______________________ ERROR collecting tests/test_gmt.py ______________________
test_gmt.py:14: in <module>
    from gmsimviz import gmt
../../../gmsimviz/gmt.py:22: in <module>
    from gmsimviz.config import config
../../../gmsimviz/config.py:8: in <module>
    with open(config_file, "r") as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '/.../gmsimviz/config.json'
```

related to the JOSS review openjournals/joss-reviews#808

**Comment by viktor76525** [comment]
_config.json_ is generated as part of running `setup.py install` which is part of the install instructions.

i have added a default to the repository to make pytest run even without installing gmsimviz

at least 2 tests will still fail unless the plotting resources are downloaded as per instructions on main github page or when `setup.py install` attempted

**Comment by viktor76525** [comment]
download archive here:
https://goo.gl/mYFCQn

exctract such that the directory exists:
`<GMSimViz repo dir>/resources`
