### ISSUE TITLE
Missing Scipy dependency

### ISSUE THREAD

**Issue by leouieda** [ucgmsim/GMSimViz#20]
The README doesn't specify it but it's included in `setup.py`. Is scipy needed?

openjournals/joss-reviews#808

**Comment by leouieda** [comment]
Trying to run the tests I see that scipy is needed. But version >=1.2.0 won't work because `scipy.misc.imread` is no longer in Scipy (https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html).

**Comment by leouieda** [comment]
Furthermore, even with scipy 1.1.0 the `pillow` library is required to access `imread` and it's not installed with scipy by default (it must be installed by the user). So it would be great to have it listed as a dependency here as well (if only an indirect one).

**Comment by viktor76525** [comment]
fixed in commit: https://github.com/ucgmsim/GMSimViz/commit/72086807e77d5726954e1f85d2084695ae65f77c
