### ISSUE TITLE
Instructions for running the tests

### ISSUE THREAD

**Issue by leouieda** [ucgmsim/GMSimViz#23]
It would be helpful to have some instructions for running the tests (including dependencies). It doesn't have to be in the README for users but maybe in CONTRIBUTING? I managed to run them but only because I read the comment in the JOSS paper review.

openjournals/joss-reviews#808

**Comment by viktor76525** [comment]
Instructions added (https://github.com/ucgmsim/GMSimViz/commit/c73eb5d976970f50d2b4e2595b6ce55c209a1a77)

**Comment by leouieda** [comment]
@viktor76525 what about the `tests/gmsimviz_compare.py` script? Is this part of the test suite?

**Comment by viktor76525** [comment]
gmsimviz_compare.py is a separate non unit-test test that runs an animation, takes a few images out and compares the amount of pixels changed
