### ISSUE TITLE
In the examples, explain which files should be generated and where

### ISSUE THREAD

**Issue by leouieda** [ucgmsim/GMSimViz#25]
The examples in the README contain the commands that should be run and the expected image/video. But there is nothing said about the files that are generated in the process or their names. One could guess from the files that suddenly pop up in the directory but it would be nice to have some mention of that in the text as well so we can be certain that we got the right output.

openjournals/joss-reviews#808

**Comment by viktor76525** [comment]
fixed (https://github.com/ucgmsim/GMSimViz/commit/2266d00a5d375a0c9d2bb011bc54de34524ec79c)
