### ISSUE TITLE
Clearer install instruction for the package (JOSS review)

### ISSUE THREAD

**Issue by leouieda** [ucgmsim/GMSimViz#6]
The install instructions show how to install the dependencies but not the GMSimViz software it self. I'm assuming that it is implied that the user should copy GMSimViz around to where the data are (or the other way around). If this is the case, there should be instructions for that. This is not ideal, though. Many users won't know where to download the source code, how to git clone or get a zip archive from Github, etc. There should instructions for this if that's the preferred install method.

A much better option would be make the GMSimViz package installable. See #4. I highly recommend doing this instead.

openjournals/joss-reviews#808

**Comment by viktor76525** [comment]
@leouieda I'm not sure having all the scripts installable is possible. GMSimViz is an MPI program and therefore requires the main script to be run with multiple processes using something like openmpi mpirun or equivalent. The qcore functions include dependencies on the main script.
Another option is copying the functions currently under qcore into GMSimViz.py
Thoughts?

**Comment by viktor76525** [comment]
expanded instructions for installing from git.
The main issue with packaging is that GMSimViz requires large geographic datasets for full functionality.
Alternatively the datasets could be hardcoded to the users home directory or system and be made optional.
