### ISSUE TITLE
Create a smaller first example (JOSS review)

### ISSUE THREAD

**Issue by leouieda** [ucgmsim/GMSimViz#8]
The example in the README is reported to take 45min to execute. This is a long time to wait if you're just trying the software out and want to see if it can be used for your project or experiment with the options. A first example should ideally be quick to run and easy to tweak for new users. It doesn't have to show every single element of the software. It can be complemented by a more detailed and longer running example.

openjournals/joss-reviews#808

**Comment by viktor76525** [comment]
two more simple examples with sample outputs added. one takes about 2 minutes, the other 12.
